<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassesRepository extends EntityRepository
{
    public function getClassesWithTeacher()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('classes')
            ->from('AppBundle:Classes', 'classes')
            ->join('classes.teacher', 'teacher')
        ->addSelect('teacher');
        return $qb->getQuery()->getResult();
    }
}
