<?php

namespace AppBundle\Repository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeachersRepository extends \Doctrine\ORM\EntityRepository
{
}
